export const LOGIN_ACTION = {
  LOGIN_ACTION_LOGIN_USER: 'LOGIN_ACTION_LOGIN_USER',
  LOGIN_ACTION_HANDLE_USER_INFO: 'LOGIN_ACTION_HANDLE_USER_INFO',
  // LOGIN_ACTION_HANDLE_PASSWORD: 'LOGIN_ACTION_HANDLE_PASSWORD'
}
