export const LOGIN_ACTION = {
  LOGIN_ACTION_LOGIN_USER: 'LOGIN_ACTION_LOGIN_USER',
  LOGIN_ACTION_HANDLE_USER_INFO: 'LOGIN_ACTION_HANDLE_USER_INFO',
}

export const HOME_ACTION = {
  HOME_ACTION_SHOW_OPTIONS: 'HOME_ACTION_SHOW_OPTIONS',
  HOME_ACTION_SELECT_OPTION: 'HOME_ACTION_SELECT_OPTION',
  HOME_ACTION_HANDLE_PUBLICATION: 'HOME_ACTION_HANDLE_PUBLICATION',
  HOME_ACTION_ADD_PUBLICATION: 'HOME_ACTION_ADD_PUBLICATION',
  HOME_ACTION_DELETE_PUBLICATION: 'HOME_ACTION_DELETE_PUBLICATION',
  HOME_ACTION_EDIT_PUBLICATION: 'HOME_ACTION_EDIT_PUBLICATION',
  HOME_ACTION_UPDATE_PUBLICATION: 'HOME_ACTION_UPDATE_PUBLICATION',
  HOME_ACTION_GET_PUBLICATIONS: 'HOME_ACTION_GET_PUBLICATIONS',
  HOME_ACTION_PUBLICATIONS_LOADED: 'HOME_ACTION_PUBLICATIONS_LOADED',
  HOME_ACTION_PUBLICATIONS_LOADED_RESET: 'HOME_ACTION_PUBLICATIONS_LOADED_RESET'
}

export const RESET_ACTION = {
  RESET_ACTION_NOW: 'RESET_ACTION_RESET_VALUES_NOW',
  RESET_OPTION_SELECTED: 'RESET_OPTION_SELECTED',
  RESET_EDIT_ACTIVE: 'RESET_EDIT_ACTIVE',
  RESET_ACTION_RESTART_ERROR_SAVE_PUBLICATION: 'RESET_ACTION_RESTART_ERROR_SAVE_PUBLICATION',
  RESET_ACTION_RESET_EDIT_PUBLICATION: 'RESET_ACTION_RESET_EDIT_PUBLICATION',
  RESET_ACTION_INPUT_VALUES: 'RESET_ACTION_INPUT_VALUES',
  RESET_ACTION_RESET_LOGIN_VALIDATION: 'RESET_ACTION_RESET_LOGIN_VALIDATION',
  RESET_ACTION_RESET_IS_INVALID: 'RESET_ACTION_RESET_IS_INVALID'
}
