export const LOGIN_ACTIONS = {
  LOGIN_ACTIONS_ADD_COMMENT: 'LOGIN_ACTIONS_ADD_COMMENT',
  LOGIN_ACTIONS_SHOW_ADD_COMMENT: 'LOGIN_ACTIONS_SHOW_ADD_COMMENT',
  LOGIN_ACTIONS_SAVE_COMMENT: 'LOGIN_ACTIONS_SAVE_COMMENT',
  LOGIN_ACTIONS_DELETE_COMMENT: 'LOGIN_ACTIONS_DELETE_COMMENT',
  LOGIN_ACTIONS_GET_COMMENTS: 'LOGIN_ACTIONS_GET_COMMENTS'
}
